Models/Group.cs
using System.Collections.Generic;
namespace Apoa.Models
{
    public class Group
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<UserGroup> GroupUsers { get; set; }

        public virtual ICollection<CategoryGroup> CategoryGroups { get; set; }


    }
}

Models/ViewModels/GroupViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace Apoa.Models.ViewModels
{
    public class GroupViewModel
    {

        public Group Group { get; set; }

        public List<Category> Categories { get; set; }
        public GroupViewModel()
        {
            Categories = new List<Category>();
        }      
        public int Year { get; set; }
    }

}

Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Apoa.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Apoa.Models.ViewModels;



namespace Apoa.Controllers
{

    [Authorize(Roles = "Opettaja")]
    public class GroupController : Controller
    {

        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> _manager;
        public GroupController(UserManager<ApplicationUser> manager, ApplicationDbContext context)
        {
            _context = context;
            _manager = manager;
        }
        public IActionResult Index()
        {
            
            ApplicationUser user = null;

            try 
            {
                user = _context.Users.Include(u => u.UserGroups)
                                            .ThenInclude(ug => ug.Group)
                                            .FirstOrDefault(u => u.Email == User.Identity.Name);

            } catch(InvalidOperationException) {

                user = null;

            }

            if (user != null)
            {

                return View(user.UserGroups.Select(ug => ug.Group).ToList());

            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> AddGroup(Group group)
        {
            string message = "Ei voi alle kolme merkkiä pitkää";
            bool status = false;

            
            
            var user = await _manager.FindByEmailAsync(User.Identity.Name);
            


            if (group != null && group.Name.Length > 2)
            {

                try
                {

                    status = true;
                    message = "Onnistui";

                    _context.Groups.Add(group);
                    _context.SaveChanges();
                    _context.UserGroups.Add(new UserGroup() { GroupId = group.Id, UserId = user.Id });
                    _context.SaveChanges();

                }
                catch (Exception)
                {

                    status = false;
                    message = "Jotain meni pieleen";
                }




                return Json(new { status = status, message = message });
            }

            return Json(new { status = status, message = message });
        }

        public ActionResult Report(int id, int year)
        {

            if (id != 0)
            {

                var group = _context.Groups.Include(g => g.CategoryGroups)
                                            .ThenInclude(cg => cg.Category)
                                            .ThenInclude(c => c.Assessments)
                                            .ThenInclude(a => a.Responses)
                                            .FirstOrDefault(g => g.Id == id);

                if (group != null)
                {

                    var model = new GroupViewModel()
                    {
                        Group = group,
                        Categories = group.CategoryGroups.Select(cg => cg.Category).ToList(),
                        Year = year
                    };

                    return View(model);
                }

            }
            return View(null);
        }

        public IActionResult GetData(int cId, int year, int groupId) {


            var group = _context.Groups.Include(g => g.CategoryGroups)
                                            .ThenInclude(cg => cg.Category)
                                            .ThenInclude(c => c.Assessments)
                                            .ThenInclude(a => a.Responses)
                                        .Include(g => g.CategoryGroups)
                                            .ThenInclude(cg => cg.Category)
                                            .ThenInclude(a => a.Assessments)
                                            .ThenInclude(a => a.ResponseOptions)
                                        .FirstOrDefault(g => g.Id == groupId);


            var categoryG = group.CategoryGroups.FirstOrDefault(c => c.CategoryId == cId);

            Category category = null;
            if (categoryG != null)
                category = categoryG.Category;

            List<Object> aData = new List<object>();
            if (category != null && category.Assessments.Count() > 0) {
                foreach (var a in category.Assessments) 
                {

                    List<Object> rData = new List<object>();
                    for(int i = 1; i <= 12; i++) {
                        var responsesInMonth = a.Responses.Where(r => r.Month == i && r.Year == year).ToList();
                        var sum = 0;
                        foreach(var r in responsesInMonth) {
                            
                            sum += r.Value;

                        }
                        try {
                            rData.Add(new {Month = i, Value = (double) sum / responsesInMonth.Count()});
                        } catch(DivideByZeroException) {
                            rData.Add(new {Month = i, Value = 0});
                        }
                    }
                    aData.Add(new { Id = a.Id,
                                    Name = a.Name,
                                    responses = rData,
                                    min = a.ResponseOptions.Min,
                                    max = a.ResponseOptions.Max});
                    
                    return Json(aData);
                }
                return Json(new {});
            }
            return Json(new {});

        }
        

    }

}

Views/Group/Index.cshtml
@model List<Apoa.Models.Group>

<div class="row">
    <div class="col-md-8">
        <h1>Ryhmät</h1>
        <form class="form-inline" style="padding-bottom: 10px; padding-top: 10px; width: 20%">
            <i class="fas fa-search" aria-hidden="true"></i>
            <input class="form-control form-control-sm ml-3 w-75" id="searchInput" type="text" onkeyup="searchGroup()" placeholder="Etsi ryhmä" aria-label="Search">
        </form>
    </div>
    <div class="form-inline col-md-4 d-flex justify-content-end"">
        <form id="groupForm">   
            <input id="Name" name="Name" class="form-control" type="text" placeholder="Lisää uusi ryhmä"/>    
        </form>
        <button data-toggle="tooltip" title="Lisää ryhmä" id="addGroup" class="btn btn-primary">
            <i class="fas fa-plus"></i>
        </button>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @if(Model != null) {
            <table id="groupTable" class="table table-striped">
                <thead>
                    <tr>
                        <th><a href="" style="color:black">Nimi</a></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var group in Model) {
                        <tr>
                            <td><a href="@Url.Action("Report", new {id = group.Id})">@group.Name</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

<script>
    $(() => {
        $(document).keypress(function(e) {
            if(e.which == 13) {
                postPress();
            }
        });

        $('[data-toggle="tooltip"]').tooltip()

        function postPress() {
            var data = $("#groupForm").serialize();
            $.post("@Url.Action("AddGroup", "Group")", data, function(res) {
                console.log(res);

                if (res.status) {
                    window.location.reload();
                } else {
                    alert(res.message)
                }
            }).fail(function() {
                alert("Jotain meni pieleen");
            });
        }

        $("#addGroup").on("click", function(e) {
            e.preventDefault();
            postPress();    
        });
    });

    function searchGroup() {
        // Declare variables
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("searchInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("groupTable");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>

Views/Group/Report.cshtml
@model Apoa.Models.ViewModels.GroupViewModel

@if(Model == null) {
    return;
}

<div class="row">
    <div class="col-md-12">
      <div class="row">
          <div class="col-md-8">
            <h1>Ryhmän vastaukset</h1>
          </div>
          <div class="col-md-4 pull-right form-inline">
            <select class="form-control" id="asty" style="width:45%;">

                @foreach(var c in Model.Categories) {
                  <option data-id="@c.Id">@c.Name</option>
                }

            </select>
            <select name="year" id="year" class="form-control" style="margin-left:20px;width:45%;">
                @for(int j = DateTime.Now.Year; j > DateTime.Now.Year - 4; j--) {
                  if(j == Model.Year) {
                    <option value="@j" selected>@j</option>
                  } else {
                      <option value="@j">@j</option>
                  }
                }
            </select>
          </div>

        </div>
        <div id="charts" data-id="@Model.Year" style="margin-top: 20px;" >
          @if(Model.Categories.Any()) {
            @foreach(var a in Model.Categories[0].Assessments) {
              <div id="chart-@a.Id"></div>
            }         
          } else {
            <p>Ei vastauksia</p>
          }
        </div>
    </div>
</div>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      function drawYear(year, cId) {
          //Käkkyrä
          console.log("before ajax")
                      
          $.get("@Url.Action("GetData")", {cId : cId, year : year, groupId : "@Model.Group.Id" }, (data) => {

              console.log("Dataa ajaxilta: ",data);
              var chartContainer = $("#charts");
              $(chartContainer).empty();
              data.map((item, index) => {
                //$(chartContainer).empty();
                $(chartContainer).append("<div class='chart-container' id='chart-" + item.id + "'</div>");

                var months = ["Tammi", "Helmi", "Maalis", "Huhti", "Touko", "Kesä", "Heinä", "Elo", "Syys", "Loka", "Marras", "Joulu"]

                var chartData = [];
                chartData.push(["Kuukausi", "Vastaus"]);

                item.responses.map((item, index) => {
                  
                  if(item.value != "NaN")
                    chartData.push([months[item.month - 1] + "kuu", item.value]);
                
                });

                var hasResponses = item.responses.every((x) => x.value == "NaN");

                  if(!hasResponses) {
                    function drawChart() {
                      // Create the data table.
                      var data = google.visualization.arrayToDataTable(chartData);
                      // Set chart options
                      var options = {
                          title: item.name,
                          legend: 'none',
                          bar: {groupWidth: '100%'},
                          vAxis: { 
                            gridlines: { count: 2 },
                            format : '0',
                            viewWindow: {
                                max: item.max,
                                min: item.min
                              }
                            },
                          hAxis: { 
                            format : '0',
                          }
                        };
                      // Instantiate and draw our chart, passing in some options.
                      var chart = new google.visualization.LineChart(document.getElementById("chart-" + item.id));
                      chart.draw(data, options);
                    }
                    google.charts.load('current', {'packages':['corechart']});
                    google.charts.setOnLoadCallback(drawChart);
                } else {
                  $("#chart-" + item.id).append("<h2>Vuodelle ei ole vastauksia</h2>");
                }
              });

            }).fail(() => {
              console.log("Jotain meni pieleen")
            })

      }
    
      $(() => {

        drawYear(@DateTime.Now.Year, $("#asty option:selected").data("id"))
        
        $("#asty").on("change",() => {
          var selected = $("#asty option:selected").data("id");
          var year = $("#year option:selected").val();

          drawYear(year, selected)
          //location.href="@Url.Action("Report",new {id=Model.Group.Id})?cId="+selected
        })

        $("#year").on("change",()=>{
          var selected = $("#asty option:selected").data("id");
          var year = $("#year option:selected").val();

          drawYear(year, selected)
        })
      })
  </script>
   